			<div id="book" class="hidden">
				<div class="arrowBack arrowBackHidden" id="back"><a href="#" id="back2" ></a></div>
				<canvas id="pageflip-canvas" width="950" height="760" style="top: -60px; left: -60px; "></canvas>
				<div id="pages">
					<section style="z-index: 6; width: 399.3085591276012px; ">
						<div>
							<h2>Indisk mat</h2>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Kyckling vindaloo" type="application/x-food"><b>Kyckling vindaloo 60 kr</b></a> (Vindaloo sås) <br/>
								Bitar av kyckling file med indisk Basmati ris, indiskt bröd, sallad, curry, grädde, indiska kryddor, kan beställas stark eller medium</p>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Kyckling curry" type="application/x-food"><b>Kyckling curry 60 kr</b></a><br/>
								Bitar av kyckling file med indisk Basmati ris, indiskt bröd, sallad, curry, grädde, indiska kryddor, kan beställas stark eller medium</p>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Kyckling Masala" type="application/x-food"><b>Kyckling Masala 60 kr</b></a><br/>
								Bitar av kyckling file med indisk Basmati ris, indiskt bröd, sallad, curry,utan grädde, indiska kryddor, kan beställas stark eller medium</p>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Butter Chicken" type="application/x-food"><b>Butter Chicken 60 kr</b></a> (med indisk buttersås)<br/>
								(Kyckling klubba) med indisk Basmati ris, indiskt bröd, sallad, curry, grädde, indiska kryddor, kan beställas stark eller medium</p>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Kyckling Tikka Masala" type="application/x-food"><b>Kyckling Tikka Masala 60 kr</b></a><br/>
								Aromatisk kryddad kycklingfile tillagad i smakfull krydsås med krossad ägg och grädde med Basmati ris, sallad</p>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Kyckling Karahi" type="application/x-food"><b>Kyckling Karahi 65 kr</b></a><br/>
								Kycklingfile tillagad med ingefära, grön chilli, tomater och paprika i en kryddig curry sås Basmati ris, sallad</p>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Kyckling Saag" type="application/x-food"><b>Kyckling Saag 60 kr</b></a><br/>
								Kycklingfile, indisk sås serveras med Basmati ris och sallad</p>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Kyckling Panear" type="application/x-food"><b>Kyckling Panear 60 kr</b></a> (med eller utan grädde)<br/>
								Vegitarisk Indisk mat (liknande feta ost) serveras med Basmati ris och sallad</p>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Shahi pannear" type="application/x-food"><b>Shahi pannear 60 kr</b></a> (med grädde)<br/>
								Vegitarisk Indisk mat (liknande feta ost) serveras med Basmati ris och sallad</p>
							</div>
						</div>
					</section>
					<section style="z-index: 5; ">
						<div>
							<h2>Pizza sida 1/4</h2>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Margarita" type="application/x-food"><b>Margarita 50 kr</b></a><br/>
								Tomat, ost
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Funghi" type="application/x-food"><b>Funghi 50 kr</b></a><br/>
								Tomat, ost, champinjoner
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Vesuvio" type="application/x-food"><b>Vesuvio 50 kr</b></a><br/>
								Tomat, ost, skinka
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Calzone" type="application/x-food"><b>Calzone 50 kr</b></a><br/>
								(Inbakad) Tomat, ost, skinka
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Capricciosa" type="application/x-food"><b>Capricciosa 50 kr</b></a><br/>
								Tomat, ost, skinka, champinjoner
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="La Gondola" type="application/x-food"><b>La Gondola 50 kr</b></a><br/>
								Tomat, ost, skinka, räkor
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Mamma Mia" type="application/x-food"><b>Mamma Mia 50 kr</b></a><br/>
								Tomat, ost, skinka, räkor, champinjoner
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Hawaii" type="application/x-food"><b>Hawaii 50 kr</b></a><br/>
								Tomat, ost, skinka, ananas
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Tropicana" type="application/x-food"><b>Tropicana 50 kr</b></a><br/>
								Tomat, ost, skinka, ananas, banan
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Quattro Stagioni" type="application/x-food"><b>Quattro Stagioni 50 kr</b></a><br/>
								Tomat, ost, skinka, champinjoner, räkor, musslor
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Marinara" type="application/x-food"><b>Marinara 50 kr</b></a><br/>
								Tomat, ost, räkor, musslor
							</div>
						</div>
					</section>
					<section style="z-index: 4; ">
						<div>
							<h2>Pizza sida 2/4</h2>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Pescatore" type="application/x-food"><b>Pescatore 50 kr</b></a><br/>
								Tomat, ost, tonfisk, lök
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Neptuno" type="application/x-food"><b>Neptuno 50 kr</b></a><br/>
								Tomat, ost, tonfisk, räkor
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Gudfaderns Pizza" type="application/x-food"><b>Gudfaderns Pizza 50 kr</b></a><br/>
								Tomat, ost, tonfisk, musslor, paprika (stark)
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Bolognese" type="application/x-food"><b>Bolognese 50 kr</b></a><br/>
								Tomat, ost, köttfärssås
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Bambino" type="application/x-food"><b>Bambino 50 kr</b></a><br/>
								Tomat, ost, köttfärssås, ananas
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="La Mafia" type="application/x-food"><b>La Mafia 50 kr</b></a><br/>
								Tomat, ost, bacon, lök, paprika
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Vegetariana" type="application/x-food"><b>Vegetariana 50 kr</b></a><br/>
								Tomat, ost, champinjoner, lök, paprika, kronärtskocka, oliver
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Cacciatore" type="application/x-food"><b>Cacciatore 50 kr</b></a><br/>
								Tomat, ost, salami, paprika
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Portofino" type="application/x-food"><b>Portofino 60 kr</b></a><br/>
								Tomat, ost, skinka, gorgonzolaost, vitlök
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Calzone Super" type="application/x-food"><b>Calzone Super 60 kr</b></a><br/>
								(Inbakad) Tomat, ost, skinka, champinjoner, räkor
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Paradiso" type="application/x-food"><b>Paradiso 60 kr</b></a><br/>
								Tomat, ost, skinka, champinjoner, räkor, ananas
							</div>
						</div>
					</section>
					<section style="z-index: 3; ">
						<div>
							<h2>Pizza sida 3/4</h2>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Bambino Super" type="application/x-food"><b>Bambino Super 60 kr</b></a><br/>
								(Inbakad) Tomat, ost, köttfärssås, lök, räkor, ananas, vitlök
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Italia" type="application/x-food"><b>Italia 60 kr</b></a><br/>
								Tomat, ost, salami, bacon, purjolök
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="El Taco" type="application/x-food"><b>El Taco 60 kr</b></a><br/>
								Tomat, ost, bacon, räkor, lök, köttfärssås, jalapeno
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Red Devil" type="application/x-food"><b>Red Devil 60 kr</b></a><br/>
								Tomat, ost, oxfile, skicka, jalapeno, bearnaisesås, grön chilli
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="El Paso" type="application/x-food"><b>El Paso 60 kr</b></a><br/>
								Tomat, ost, champinjoner, räkor, oxfile, jalapeno, bearnaisesås
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Galgamarken Special" type="application/x-food"><b>Galgamarken Special 60 kr</b></a><br/>
								Tomat, ost, marinerad oxfile, champinjoner, bearnaisesås, curry
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Ciao Ciao" type="application/x-food"><b>Ciao Ciao 60 kr</b></a><br/>
								Tomat, ost, marinerad oxfile, champinjoner, kronärtskocka, vitlök
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Festpizza" type="application/x-food"><b>Festpizza 60 kr</b></a><br/>
								Tomat, ost, marinerad oxfile, champinjoner, sparis, bearnaisesås
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Trossö Special" type="application/x-food"><b>Trossö Special 60 kr</b></a><br/>
								Tomat, ost, marinerad oxfile, champinjoner, lök, salami, stark och vitlöksås
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Indiana" type="application/x-food"><b>Indiana 60 kr</b></a><br/>
								Tomat, ost, marinerad oxfile, banan, curry
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Fiskarens Pizza" type="application/x-food"><b>Fiskarens Pizza 60 kr</b></a><br/>
								Tomat, ost, krabba, räkor, tonfisk, musslor
							</div>
						</div>
					</section>
					<section style="z-index: 2; ">
						<div>
							<h2>Pizza sida 4/4</h2>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Gorgonzola" type="application/x-food"><b>Gorgonzola 60 kr</b></a><br/>
								Tomat, ost, marinerad oxfile, champinjoner, gorgonzolaost
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Mexicana" type="application/x-food"><b>Mexicana 60 kr</b></a><br/>
								Tomat, ost, bacon, köttfärssås, lök, paprika (stark)
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Lambada" type="application/x-food"><b>Lambada 60 kr</b></a><br/>
								Tomat, ost, marinerad oxfile, champinjoner, bacon, skinka, köttfärssås, bearnaisesås
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Pino" type="application/x-food"><b>Pino 60 kr</b></a><br/>
								Tomat, ost, marinerad oxfile, fläskfile, jalapeno (stark)
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Valentino Special" type="application/x-food"><b>Valentino Special 60 kr</b></a><br/>
								Tomat, ost, fläskfile, lök, champinjoner, bearnaisesås
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Kebabpizza" type="application/x-food"><b>Kebabpizza 60 kr</b></a><br/>
								Tomat, ost, kebabkött, lök, sallad, pfefferoni (stark eller svag sås)
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Kebabpizza Special" type="application/x-food"><b>Kebabpizza Special 60 kr</b></a><br/>
								(Inbakad) Tomat, ost, kebabkött, lök, sallad, pfefferoni (stark eller svag sås)
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Venezia" type="application/x-food"><b>Venezia 60 kr</b></a><br/>
								Tomat, ost, kebabkött, skinka, lök (stark eller svag sås)
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Gyrospizza Special" type="application/x-food"><b>Gyrospizza Special 60 kr</b></a><br/>
								Tomat, ost, gyroskött, lök, sallad, pfefferoni (stark eller svag sås)
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Marco Polo" type="application/x-food"><b>Marco Polo 60 kr</b></a><br/>
								Tomat, ost, marinerad oxfile, purjolök, bearnaisesås, vitlök, champinjoner
							</div>
						</div>
					</section>
					<section style="z-index: 1; ">
						<div>
							<h2>Kebab/Gyros/Hamburgare</h2>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Kebab med Bröd" type="application/x-food"><b>Kebab med Bröd 45 kr</b></a><br/>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Kebabrulle" type="application/x-food"><b>Kebabrulle 50 kr</b></a><br/>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Kebabrulle Special" type="application/x-food"><b>Kebabrulle Special 55 kr</b></a><br/>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Kebabtallrik" type="application/x-food"><b>Kebabtallrik 50 kr</b></a><br/>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Kebabtallrik Special" type="application/x-food"><b>Kebabtallrik Special 55 kr</b></a><br/>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Gyros med Bröd" type="application/x-food"><b>Gyros med Bröd 50 kr</b></a><br/>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Gyrosrulle" type="application/x-food"><b>Gyrosrulle 55 kr</b></a><br/>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Gyrostallrik" type="application/x-food"><b>Gyrostallrik 55 kr</b></a><br/>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Hamburgare 90g" type="application/x-food"><b>Hamburgare 90g 40 kr</b></a><br/>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Hamburgare 150g" type="application/x-food"><b>Hamburgare 150g 50 kr</b></a><br/>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Hamburgaretallrik 90g" type="application/x-food"><b>Hamburgaretallrik 90g 50 kr</b></a><br/>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="Hamburgaretallrik 150g" type="application/x-food"><b>Hamburgaretallrik 150g 60 kr</b></a><br/>
							</div>
							<div>
								<p><a href="#" onclick="pickItem(this)" name="FRITEXT" type="application/x-food"><b>Klicka för skriva fritext</b></a><br/>
							</div>
						</div>
					</section>
				</div>
				<div class="arrowNext arrowNextHidden" id="next"><a href="#" id="next2" ></a></div>
			</div>
			<script src="js/pageflip.js"></script>


