
<a href="/order/summary">Sammanställning</a>

<form action="/order/add" method="POST">

<table>

<tr title="Om du vill betala med Payson så kan du lika gärna ange din e-postadress här direkt.">
<td><label for="person">UID/e-postadress</label></td>
<td><input name="person" type="text"/></td>
</tr>

<tr>
<td><label for="base_dish">Maträtt</label></td>
<td><input name="base_dish" type="text" value="Vindaloo"/></td>
</tr>

<tr>
<td><label for="rice">Ris? </label></td>
<td><input name="rice" type="checkbox" value="1" checked="checked"/></td>
</tr>

<tr>
<td><label for="power">Styrka</label></td>
<td>
<select name="power" style="width:100%;">
<option value="medium">Medium</option>
<option value="hot">Stark</option>
<option value="xhot">Extra Stark</option>
</select>
</td>
</tr>

<tr>
<td><label for="drink">Dryck</label></td>
<td>
<select name="drink" style="width:100%;">
<option value="naturell">Mineralvatten Naturell</option>
<option value="citrus">Mineralvatten Citrus</option>
<option value="cola">Coca-Cola</option>
<option value="cola light">Coca-Cola Light</option>
<option value="fanta">Fanta</option>
<option value="sprite">Sprite</option>
</select>
</td>
</tr>

<tr>
<td><label for="paid_to">Betalt till person</label></td>
<td>
<select name="paid_to" style="width:100%;">
<option value="">(ingen)</option>
<optgroup label="Snabbval">
<option value="David">David</option>
<option value="xfrehaa">Fredrik Håård</option>
</optgroup>
<optgroup label="Alla">
<?php foreach ($this->people as $person): ?>
<option value="<?= $this->escape($person); ?>"><?= $this->escape($person); ?></option>
<?php endforeach; ?>
</optgroup>
</select>
</td>
</tr>

<td>&nbsp;</td>
<td><input name="add" type="submit" value="Lägg till beställning"/></td>

</table>

</form>
