<h1>Indiskt <?= $this->today ?></h1>

<p>Totalt antal beställningar: <?= count($this->all); ?></p>

<h2>Personer som hämtar mat</h2>

<table>
<th>Person</th>
<th>Kontanter</th>
<th>Antal att betala för</th>
<?php foreach ($this->payAgentSummary as $entry): ?>
<tr>
<td><?= $entry->paid_to ?></td>
<td><?= $entry->paid_sum ?></td>
<td><?= $entry->count ?></td>
</tr>
<?php endforeach; ?>
<tr><td colspan="3"><hr/></td></tr>
<?php foreach ($this->unpaidSummary as $entry): ?>
<tr>
<td><?= $entry->person ?></td>
<td>&nbsp;</td>
<td>1</td>
</tr>
<?php endforeach; ?>
</table>



<h2>Matbeställning</h2>

<p>Telefonnummer: 0455-311002</p>

<table>
<?php foreach ($this->foodSummary as $entry): ?>
<tr>
<td><?= $entry->count ?></td>
<td><?= $entry->base_dish ?></td>
<td><?= $entry->power ?></td>
<td><?= $entry->rice ? 'Med ris' : 'Utan ris' ?></td>
</tr>
<?php endforeach; ?>
</table>

<h2>Dryck</h2>

<table>
<?php foreach ($this->drinkSummary as $entry): ?>
<tr>
<td><?= $entry->count ?></td>
<td><?= $entry->drink ?></td>
</tr>
<?php endforeach; ?>
</table>

<h2>Vem beställde vad?</h2>

<table>
<?php foreach ($this->all as $entry): ?>
<tr>
<td><a href="/order/show?person=<?= $this->escape($entry->person) ?>"><?= $this->escape($entry->person) ?></a></td>
<td><?= $entry->base_dish ?></td>
<td><?= $entry->power ?></td>
<td><?= $entry->rice ? 'Med ris' : 'Utan ris' ?></td>
<td><?= $entry->drink ?></td>
<!-- <td><?= $entry->amount_paid ?></td> -->
<td><?= $entry->paid_to ?></td>
<?php if (empty($entry->paid_to) || $entry->paid_to == 'David'): ?>
<td><a href="/payson/payment?refNr=<?= $entry->id ?>&email=<?= $this->escape($entry->person) ?>" title="7 kr i avgift tillkommer">Betala till David via Payson</a></td>
<?php endif; ?>
</tr>
<?php endforeach; ?>
</table>


